import { useAuth } from '../context/AuthContext'
import { useExpense } from '../context/ExpenseContext'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { jsPDF } from 'jspdf'

function Profile() {
  const { user, logout } = useAuth()
  const { transactions } = useExpense()

  /* ---------- CALCULATIONS ---------- */
  const income = transactions
    .filter(t => t.amount > 0)
    .reduce((sum, t) => sum + t.amount, 0)

  const expense = transactions
    .filter(t => t.amount < 0)
    .reduce((sum, t) => sum + Math.abs(t.amount), 0)

  const net = income - expense

  /* ---------- PDF DOWNLOAD ---------- */
  function downloadProfilePDF() {
  const doc = new jsPDF()

  /* ---------- COLORS ---------- */
  const primary = [37, 99, 235]
  const dark = [15, 23, 42]
  const gray = [100, 116, 139]
  const green = [22, 163, 74]
  const red = [220, 38, 38]

  /* ---------- HEADER ---------- */
  doc.setFontSize(22)
  doc.setTextColor(...primary)
  doc.text('CashFlow – Profile Summary', 105, 20, { align: 'center' })

  doc.setFontSize(10)
  doc.setTextColor(...gray)
  doc.text(
    `Generated on ${new Date().toLocaleDateString()}`,
    105,
    28,
    { align: 'center' }
  )

  /* ---------- AVATAR ---------- */
  doc.setDrawColor(...primary)
  doc.setLineWidth(1)
  doc.circle(105, 48, 10)
  doc.setFontSize(12)
  doc.setTextColor(...primary)
  doc.text(user?.name?.charAt(0)?.toUpperCase() || 'U', 105, 52, {
    align: 'center',
  })

  /* ---------- PROFILE CARD ---------- */
  doc.roundedRect(20, 65, 170, 35, 8, 8)
  doc.setFontSize(12)
  doc.setTextColor(...dark)
  doc.text('Profile Details', 25, 75)

  doc.setFontSize(11)
  doc.setTextColor(...gray)
  doc.text('Name', 25, 85)
  doc.text('Phone', 25, 95)

  doc.setTextColor(...dark)
  doc.text(`: ${user?.name || 'User'}`, 70, 85)
  doc.text(`: +91 ${user?.phone}`, 70, 95)

  /* ---------- FINANCIAL SUMMARY ---------- */
  doc.roundedRect(20, 110, 170, 70, 8, 8)
  doc.setFontSize(12)
  doc.setTextColor(...dark)
  doc.text('Financial Summary', 25, 120)

  const startY = 135

  doc.setFontSize(11)
  doc.setTextColor(...gray)
  doc.text('Total Income', 25, startY)
  doc.text('Total Expense', 25, startY + 15)
  doc.text('Net Savings', 25, startY + 30)

  doc.setTextColor(...green)
  doc.text(`₹ ${income.toLocaleString()}`, 110, startY)

  doc.setTextColor(...red)
  doc.text(`₹ ${expense.toLocaleString()}`, 110, startY + 15)

  doc.setTextColor(net >= 0 ? green[0] : red[0], net >= 0 ? green[1] : red[1], net >= 0 ? green[2] : red[2])
  doc.text(`₹ ${net.toLocaleString()}`, 110, startY + 30)

  /* ---------- VISUAL BAR CHART ---------- */
  const max = Math.max(income, expense)
  const barWidth = 120

  doc.setTextColor(...dark)
  doc.text('Income vs Expense', 25, 195)

  // Income bar
  doc.setFillColor(...green)
  doc.rect(25, 200, (income / max) * barWidth, 8, 'F')
  doc.text('Income', 150, 206)

  // Expense bar
  doc.setFillColor(...red)
  doc.rect(25, 215, (expense / max) * barWidth, 8, 'F')
  doc.text('Expense', 150, 221)

  /* ---------- FOOTER ---------- */
  doc.setFontSize(9)
  doc.setTextColor(...gray)
  doc.text(
    'Generated by CashFlow • Personal Finance Dashboard',
    105,
    285,
    { align: 'center' }
  )

  doc.save('CashFlow_Profile.pdf')
}

  return (
    <div className="profile-page">

      {/* ---------- PROFILE BAR ---------- */}
      <div className="profile-bar card">
        <div className="profile-left">
          <div className="profile-avatar">
            <FontAwesomeIcon icon="user" />
          </div>

          <div className="profile-info">
            <h3>{user?.name || 'User'}</h3>
            <p>+91 {user?.phone}</p>
            <span className="profile-meta">
              Logged in via OTP
            </span>
          </div>
        </div>

        <button
          className="btn-outline"
          onClick={downloadProfilePDF}
        >
          <FontAwesomeIcon icon="download" /> Download PDF
        </button>
      </div>

      {/* ---------- STATS ---------- */}
      <div className="profile-stats">
        <div className="card stat positive">
          <p>Total Income</p>
          <h3>₹{income}</h3>
        </div>

        <div className="card stat negative">
          <p>Total Expense</p>
          <h3>₹{expense}</h3>
        </div>

        <div className="card stat">
          <p>Net Savings</p>
          <h3 className={net >= 0 ? 'positive' : 'negative'}>
            ₹{net}
          </h3>
        </div>
      </div>

      {/* ---------- ACCOUNT ACTIONS ---------- */}
      <div className="card profile-actions">
        <h4>Account Actions</h4>

        <button
          className="danger-btn"
          onClick={logout}
        >
          <FontAwesomeIcon icon="right-from-bracket" />
          Logout
        </button>
      </div>

      {/* ---------- SECURITY ---------- */}
      <div className="card profile-security">
        <h4>Security</h4>

        <div className="security-row">
          <span>Phone</span>
          <span>+91 {user?.phone}</span>
        </div>

        <div className="security-row">
          <span>Login Method</span>
          <span>OTP Authentication</span>
        </div>
      </div>

    </div>
  )
}

export default Profile
